In [4]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [10]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [11]:
df = pd.read_csv("complaint_severity_dataset - complaint_severity_dataset_12k (1).csv")

df.head()

                                             message  label
0       Payment taken multiple times! kindly resolve      2
1  Serious complaint: wrong person received my or...      2
2                Need help with changing my address.      1
3  Urgent: money deducted but order failed! pleas...      2
4                 Your staff was polite. please help      0

In [12]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):

    # Lowercase conversion
    text = text.lower()

    # Remove punctuation & special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Tokenization
    tokens = word_tokenize(text)

    # Stopword removal + Lemmatization
    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
        if word not in stop_words
    ]

    return " ".join(tokens)

In [13]:
df["clean_message"] = df["message"].apply(preprocess_text)

df[["message", "clean_message"]].head()

,message,clean_message
0,Payment taken multiple times! kindly resolve,payment taken multiple time kindly resolve
1,Serious complaint: wrong person received my or...,serious complaint wrong person received order ...
2,Need help with changing my address.,need help changing address
3,Urgent: money deducted but order failed! pleas...,urgent money deducted order failed please help
4,Your staff was polite. please help,staff polite please help

In [14]:
for i in range(5):
    print("Original :", df["message"][i])
    print("Processed:", df["clean_message"][i])
    print("-"*80)

Original : Payment taken multiple times! kindly resolve
Processed: payment taken multiple time kindly resolve
--------------------------------------------------------------------------------
Original : Serious complaint: wrong person received my order and details!!!!
Processed: serious complaint wrong person received order detail
--------------------------------------------------------------------------------
Original : Need help with changing my address.
Processed: need help changing address
--------------------------------------------------------------------------------
Original : Urgent: money deducted but order failed! please help
Processed: urgent money deducted order failed please help
--------------------------------------------------------------------------------
Original : Your staff was polite. please help
Processed: staff polite please help
--------------------------------------------------------------------------------

In [15]:
df.to_csv("cleaned_complaints.csv", index=False)

print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully

In [16]:
df[['message','clean_message']].head()

,message,clean_message
0,Payment taken multiple times! kindly resolve,payment taken multiple time kindly resolve
1,Serious complaint: wrong person received my or...,serious complaint wrong person received order ...
2,Need help with changing my address.,need help changing address
3,Urgent: money deducted but order failed! pleas...,urgent money deducted order failed please help
4,Your staff was polite. please help,staff polite please help